### ISSUE TITLE
Points being removed after processing

### ISSUE THREAD

**Issue by james2432** [openstreetcam/openstreetview.org#105]
I would finish uploading a track and see I got my points. After processing has completed i'd be left with nothing:

![image](https://cloud.githubusercontent.com/assets/498547/22889697/12bfb5fc-f1d8-11e6-8cd8-72034587cc2d.png)

The only way I found to fix it is to send the "finished upload" for that track so my points would be calculated:

![image](https://cloud.githubusercontent.com/assets/498547/22889759/3e913228-f1d8-11e6-8d6d-9873fd36d381.png)

I know they are not being counted as I go to the leaderboard:
![image](https://cloud.githubusercontent.com/assets/498547/22889854/853d9478-f1d8-11e6-8062-0082290bb5ac.png)
after I set some as being complete:
![image](https://cloud.githubusercontent.com/assets/498547/22889882/9bea37b2-f1d8-11e6-80a2-0e073d8e2e19.png)

**Comment by james2432** [comment]
All my recordings since: Feb 06, 2017 were broken. The previous of the 6th that was "OK" was : Feb 03, 2017, but everyone since the 6th was missing the points

**Comment by ToeBee** [comment]
I thought I had some sequences that just didn't get points assigned but they may be the same as you found. The affected ones are dated January 29th through February 4th.

**Comment by ToeBee** [comment]
I just tried sending the upload finish POST like you mentioned above on my 4 affected sequences and it did indeed work to get the points working again. In fact, doing so bumped me up to level 15 in the scoring system :)

If anyone else is wondering, you can do this with the following curl command:

    curl -X POST -F access_token=yourtoken -F sequenceId=1234 http://openstreetview.com/1.0/sequence/finished-uploading/

where `yourtoken` is the contents of the access_token.txt file that gets left in the directory that you run the upload script from and `1234` is the ID of the sequence that you can get from the URL when viewing one of the pictures in the sequence.
