### ISSUE TITLE
No way to upload images via the website

### ISSUE THREAD

**Issue by jidanni** [openstreetcam/openstreetview.org#114]
Let's say the user has 1000 EXIF geotagged JPG images he would like to contribute to the site.

Well there is no way to upload them via the website.

**Comment by james2432** [comment]
There are multiple ways to do so:
1. Official upload scripts: https://github.com/openstreetcam/upload-scripts
2. Official GUI Interface(needs compiling) : https://github.com/openstreetcam/upload-GUI
3. OSVUploadr (GUI Created by me in java(multiplatform)) : https://github.com/osmottawa/OSVUploadr/releases

**Comment by mprins** [comment]
I just tried number 3 and it fails, see osmottawa/OSVUploadr#13

**Comment by mprins** [comment]
hmm 1. also just keeps logging `Retry attempt : nnn`  where `nnn` just keeps adding up.... I stopped it at ~1000...

**Comment by bogdan-telenav** [comment]
@mprins Can you share some images to debug. Thanks for reporting 👍

**Comment by james2432** [comment]
Specifically:
/mnt/tera1/mapillary/SD-kaart/Android/data/app.mapillary/files/mapillary/__uploaded_web/2017_04_26_11_16_19_768/2017_04_26_11_18_19_182.jpg

As it's the first one you try to upload and the server returns error 400 (might be missing some information)

**Comment by mprins** [comment]
I've tried the python script () for uploading which does upload, but it seems the sequence gets garbled, see:   http://www.openstreetcam.org/details/165078/114

A handful of images is available for download at: https://we.tl/M5hmilH9bP

**Comment by james2432** [comment]
Seems to not have compass angle/heading:

![image](https://cloud.githubusercontent.com/assets/498547/25622774/94d73046-2f23-11e7-84f4-600977eec217.png)

**Comment by mprins** [comment]
I wasn't aware images should have heading the docs just mention geotagged images imo that does not include direction

**Comment by james2432** [comment]
@bogdan-telenav I think it may be the way the file time is set in the EXIF data:
https://github.com/osmottawa/OSVUploadr/issues/13#issuecomment-298696900
I've created a way of determining which to use(for ordering purposes):
https://github.com/osmottawa/OSVUploadr/blob/0.1.3-ALPHA/OSVUploadr/src/main/java/ca/osmcanada/osvuploadr/Utils/Helper.java#L81

**Comment by bogdan-telenav** [comment]
@mprins geotagged are enough to upload them. Heading is something nice to have.
I hope today i will find where is the problem and fix it.
As @james2432 said the sort by some timestamp is the problemw

**Comment by bogdan-telenav** [comment]
@mprins I tested why your images. They upload fine. http://www.openstreetcam.com/details/165268/0  - you can test this trip after some time. After you check this let me know so i will delete my upload. 


<img width="1509" alt="screen shot 2017-05-03 at 11 50 32 am" src="https://cloud.githubusercontent.com/assets/18165943/25653792/1ce07316-2ff7-11e7-98fb-50aaf18aa3f3.png">

<img width="887" alt="screen shot 2017-05-03 at 11 51 14 am" src="https://cloud.githubusercontent.com/assets/18165943/25653793/1ce6b550-2ff7-11e7-8754-5bfe8a791b1b.png">

**Comment by james2432** [comment]
Another issue with the photos, is it doesn't follow the spec for exif directories:
https://github.com/osmottawa/OSVUploadr/issues/13#issuecomment-299525056
Asus decided they would put everything in IF0 Directory instead of correctly putting it in the Sub IFD Directory as is specification

**Comment by bogdan-telenav** [comment]
Hmm i don't have for now any Asus to test on. However i will try to simulate this problem somehow. Thanks for reporting.

**Comment by mprins** [comment]
I've updated the Mapillary app as well as my workflow (geotag in gottengeography, add interpolated gps image direction if applicable, upload using script) and that seems to work fine. eg. http://www.openstreetcam.org/details/449347/0 so I think this can be closed

**Comment by bogdan-telenav** [comment]
@mprins I'm happy that this works for you fine 👍.
