### ISSUE TITLE
iOS Missing Photos/Second Trip "Records" but no images

### ISSUE THREAD

**Issue by roadgeek** [openstreetcam/openstreetview.org#115]
I noticed that the second trip (of two) is often getting lost.  Typical scenario: I start and stop a trip on the way to lunch, surf the web or text message while waiting in line, and then start and stop another trip on the way back to the office.  When I go to upload, I see only the first trip.  If I leave OpenStreetCam and the compass app (for leveling the camera) open and **don't** surf or text or close down those apps, it appears to save the second trip.  I am still trying to figure out the exact steps that cause a recorded trip to disappear.

Hitting record will sometimes give me a few, one or zero pictures for a run.  Another example: Trip of 40 kms yields only 6 pictures: http://openstreetcam.org/details/331672/3 with a 40 km gap between 4 and 6.

OSC build: 1.5.3(1)
iOS: 10.3.1
Available memory: 42.7 Gb

**Comment by roadgeek** [comment]
Noticed that the iPhone was overheating.  Tried without case and no power cord with no change.  After turning off "Detect Road Signs", it seems to be appears to be stable.  Several hour long runs without any issues (but still waiting for process/up load).

**Comment by bogdans-telenav** [comment]
@roadgeek  the iOS dev. 
Can you please use the latest iOS build at the moment is: 1.5.7(1).
We had some bugs that might explain "loosing a trip" 
I can confirm that using the map and the "Detect road signs" can make the phone really hot. 
If your phone is still getting hot you can further deactivate the map while recording, points.
If you would like to have longer trips without charging you can remove the map altogether from settings and deactivate all above.

**Comment by bogdans-telenav** [comment]
Also the latest build has a fix for the gap bug. Basically there was a bug in the app when driving with the OBD connected sometimes the app did not make photos.
This was fixed in a previous build so it is working in build 1.5.7.

**Comment by roadgeek** [comment]
@bogdans-telenav: Thanks for the reply.  For the overheating, I also disabled the map.  I just downloaded 1.5.6 (1) via TestFlight, but hadn't seen an E-mail that it was released.

Does disabling the points on the phone have any effect of getting points on the website?

**Comment by bogdans-telenav** [comment]
@roadgeek  Disabling the points on the phone does not effect getting points on the website, it just disables the phone estimation and removes the Leaderbord item from the main menu.
