### ISSUE TITLE
report images / users

### ISSUE THREAD

**Issue by grinapo** [openstreetcam/openstreetview.org#120]
Now what should I just say now?
http://openstreetcam.org/user/kali113xd
[Pinggau is believable, but Ottkaring?]

**Comment by kalmanbencze** [comment]
Yeah we're going to punish these accounts with a firm hand. It's not ok to upload junk data. Did you report the account?

**Comment by kalmanbencze** [comment]
BTW thats me, so yeah I have a bit of a cleanup and explainin' to do...

**Comment by grinapo** [comment]
@kalmanbencze well to report it would require some way to report an account, doesn't it? I checked around for 10 minutes but found none, neithe for accounts nor for individual images or sequences (or whatever you call a continuous stream).

(As for the specific individual, well, go and have a serious talk with him [kétszemközt]. :-))

**Comment by bogdans-telenav** [comment]
i am closing this but suggesting a improvement for the project to have some way to report a image/ account.
