### ISSUE TITLE
Tracks visible in user profile but not on map

### ISSUE THREAD

**Issue by GeoKitten** [openstreetcam/openstreetview.org#130]
I am a relatively new OSC user (my username there is GeoKitten, just like here) and I have uploaded 13 tracks so far. All of them have finished uploading and processing but only one has appeared on the map so far. The oldest tracks that are not appearing were recorded a day and a half ago and they're still not showing up. I cannot be 100% sure that this is abnormal, but as a new contributor this concerns me because no one will be able to see my images.

Basic technical details: The sets of images are missing from openstreetcam.org but they show up in my profile, unlike the person who filed a similar issue. They also show up in the JOSM plugin when you zoom in enough to show individual images.

**Comment by GeoKitten** [comment]
All of my imagery are visible now. It just took longer than I expected for the map to update and I got worried too soon. I apologize for the confusion. But it's just like OSM where it can take some time for new stuff to appear, especially at lower zooms.

Now I know that it can take a few days for new contributions to show up, but I suggest that someone should write this in whatever Openstreetcam tutorials that exists in order to avoid confusing other newbies.

**Comment by alexandrui-telenav** [comment]
Sorry about that @GeoKitten ( great username by the way! ). In peak times it takes a bit of time for the map to reflect new recordings. Working on improving that.
