### ISSUE TITLE
Multiple tracks dont have points calculated

### ISSUE THREAD

**Issue by smajser** [openstreetcam/openstreetview.org#131]
Hi,

User:    Smajser
I have 5 tracks that points are not calculated on.
All tracks are on the map and correctly positioned

Best regards
Uros Racic

**Comment by alexandrui-telenav** [comment]
Hi @smajser,

Sorry about that, the problem is now resolved. Great photos!

Alex

**Comment by smajser** [comment]
Hi Alex,

thanks for fast replay and problem solving. I have few questions.

1) is there some way that application can capture images faster? 
Mapillary has options to adjust capture setting, but in OSC i dont see 
it.
2) is there some way that I can upload pictures that are captured for 
Mapillary to be used for OSC?
3) please check "Skobbler Dev" account. There is a lot of pictures that 
I can not relate to street imaging by any means.


Best regards
Uros Racic




G:  smajser1
S:  uros.racic
P:  +381 63 45-48-45
L:   https://www.linkedin.com/in/uros-racic-0a9555120/
T:   @racic_uros



------ Original Message ------

**Comment by bogdan-telenav** [comment]
Hi @smajser 

I can help you with: 2) problem .
Here https://github.com/openstreetcam/upload-scripts/tree/master/upload_photos_by_exif is a python script that you can use for that type of images

Thanks for mapping and have fun
Bogdan Racasan

**Comment by smajser** [comment]
Hi Racasan,

I have download script and python and it does not work.
I am not familiar with python, so if you can explain me a bit it would 
be great.



G:  smajser1
S:  uros.racic
P:  +381 63 45-48-45
L:   https://www.linkedin.com/in/uros-racic-0a9555120/
T:   @racic_uros

------ Original Message ------
