### ISSUE TITLE
Points not calculated correctly on images uploaded using the python scripts

### ISSUE THREAD

**Issue by ToeBee** [openstreetcam/openstreetview.org#134]
After uploading images using the `upload_photos_by_exif.py`, they all show up as being on roads with 10+ coverage and are assigned one point per image, even when I know there are far fewer than 10 traces along the route (sometimes none)

This has been happening on and off for a couple of weeks I think but it seemed like some script came through and recalculated things periodically. However I now have 51 tracks with incorrect point totals. Some were uploaded a week ago. The last one with correct points on it was uploaded on August 1st. It's just all the recent uploads visible at http://openstreetcam.com/user/ToeBee

I might have come in as #1 uploader by points for last week if the points had been scored correctly last week :)

**Comment by ToeBee** [comment]
One of the traces has an odd discrepancy. There were 231 pictures in the trace but in the points section of the display it says there were 304 pictures and it has been assigned 304 points. http://openstreetcam.com/details/513457/0

**Comment by ToeBee** [comment]
This is still happening. All of my recent uploads are assigned to the "10+" bucket even though most of them have at most 1-2 existing traces along them. And the number reported in the points section does not match the number of actual pictures in the track:
![image](https://user-images.githubusercontent.com/348948/32059698-8a87fc66-ba32-11e7-88bf-4e022d95a34b.png)

**Comment by alexandrui-telenav** [comment]
Hi @ToeBee , sorry to see that happening and the late response. We'll take a look early next week, it seems to be a bug in the geotagged JPEGs processing. Will reply next week with a resolution.

**Comment by ToeBee** [comment]
Any progress? I'm about ready to dump about 24,000 pictures on you. Would be nice to see correct points on the weekly leaderboard for it :)

**Comment by ToeBee** [comment]
It seems like this might be fixed for newly uploaded tracks. I just finished an upload of 4,084 pictures and got 33,716 points! And the picture counts match up too.

All my uploads between August 2nd and October 26th could do with a recalculation on points though.

**Comment by alexandrui-telenav** [comment]
@ToeBee , it took a while but yes. Fixed the new tracks about a week ago and now we ran it for all historic data. You just got a few million points more and a jump to #4 overall OSC contributor!
Sorry about that and kudos for all the 776k photos! 👍
