### ISSUE TITLE
Where did you hide the upload form?

### ISSUE THREAD

**Issue by bitnapper** [openstreetcam/openstreetview.org#138]
I take a lot of photos for Mapillary and I'd like to upload them on OSC as well but I cant find a working upload form on the website.

**Comment by james2432** [comment]
There are 3 ways you can upload to OSC:
1. https://github.com/openstreetcam/upload-scripts/tree/master/upload_photos_by_exif Python upload script
2.https://github.com/openstreetcam/upload-GUI C++ GUI needs manual compilation
3.https://github.com/osmottawa/OSVUploadr/releases Java Multiplatform GUI I made. No compiling required

These require that each trip be in a disinct folder

**Comment by alexandrui-telenav** [comment]
@bitnapper sorry, no web upload form for now. Just the options @james2432 described ( thanks james ).
