### ISSUE TITLE
Error Loading image

### ISSUE THREAD

**Issue by muzirian** [openstreetcam/openstreetview.org#141]
Getting "error loading image" for lots of sequences in josm, none of the images load on that sequence, but nearby sequences work.Its not loading by default on browser also.

For example, the link to image goes to

http://internal.openstreetcam.org/details/9325/1076

but if i edit out internal part from url it works.

**Comment by alexandrui-telenav** [comment]
Hi @muzirian , I can't say for sure what the exact problem was, but now it seems to be resolved.
