### ISSUE TITLE
Extracting images around gps location

### ISSUE THREAD

**Issue by bkvie** [openstreetcam/openstreetview.org#145]
Is their a method to extract images around a GPS location other than taking them from the plugin or via HTTP request? I would be willing to write/extend a python API.

**Comment by alexandrui-telenav** [comment]
http://openstreetcam.org/api/doc.html#operation--nearby-tracks-post 
Would this work?

**Comment by joshinils** [comment]
that link doesn't exists anymore :frowning_face:
