### ISSUE TITLE
corrupted image tiles

### ISSUE THREAD

**Issue by andrewharvey** [openstreetcam/openstreetview.org#146]
Viewing the main site the image tiles are corrupted, downloading the image tiles and opening in `eog` still shows the corrupted tiles so looks like an upstream issue?

![osc](https://user-images.githubusercontent.com/117278/32686768-e741cb92-c6ff-11e7-9b3a-eff917e99f88.png)

**Comment by alexandrui-telenav** [comment]
Yep. OSC is using the skobbler/Tnav tileserver that is having some issues recently. I raised this and got word that should be resolved, but we'll monitor to make sure it's the case. Sorry about this, if the problem persists we'll think about options regarding map tiles..
