### ISSUE TITLE
App Stops Capturing Footage

### ISSUE THREAD

**Issue by gregoryopera** [openstreetcam/openstreetview.org#147]
When I use OpenStreetCam 2.1.5 on my Sony G3226 Xperia XA1 Ultra (Android 7.0, Build 42.0.A.4.101), the application "freezes" recording after approximately 70-90MB has been captured (it varies). The application itself is fine and OpenStreetCam even says it is still recording - but the file-size does not get any bigger and when I stop the video at the end of my trip, it can easily be confirmed that capture had indeed stopped.

In saying this, when I stop the video, it just sits there with a "spinning circle" on the recording button, and I must either restart my smartphone or forcefully close the application - I find that if I do not restart my smartphone though, other applications think OpenStreetCam is still using the camera, after I have closed the application.

At first I thought it might be because my smartphone was overheating, even though it doesn't actually feel excessively warm... But I have been able to record over twenty minutes of footage with Sony's own "camera" application, at the best-quality settings.

Therefore, the issue most likely lies with this application.

Can we please get OpenSteetView updated to address this issue?

**Comment by james2432** [comment]
Have you tried switching to JPEG recording? I've had issues with budget phones not able to keep up in processing sense when video capture is enabled. JPEG recording is much less CPU intensive

**Comment by gregoryopera** [comment]
JPEG recording works... But unlike "regular" recording, it makes my smartphone get ridiculously hot after 10-15 minutes - so hot in fact, that the camera shuts down until the smartphone has cooled.

So JPEG is a work-around... But only sort of.

Like I said, I can record video for 20+ minutes using Sony's included camera application on the highest-quality settings, so it's gotta be something to do with this particular application...

**Comment by alexandrui-telenav** [comment]
@gregoryopera, could you possibly report an issue from the app ( Settings-> Report a problem ) for the recording freeze? That also sends us the app's logs from the last 48h, if the event happened in that interval we should be able to pinpoint the problem.

I can confirm there's a problem in the app  related to the camera open/close which we'll investigate in our next sprint, sorry about that.
What I suggest is to reduce the photo resolution, even 2 MP is fine for detecting traffic signs and road info.
