### ISSUE TITLE
Using IPFS to host OSC imagery

### ISSUE THREAD

**Issue by vr00n** [openstreetcam/openstreetview.org#150]
Any plans on using the InterPlanetary File System to host OSC imagery in a distributed manner?

Looks like a great use case. See more at http://ipfs.io

After all won't be long before we need to think about using open street cam on Martian roads ;)

**Comment by alexandrui-telenav** [comment]
Seems like an interesting concept, but we're focusing on building maps from the data for the foreseeable future. Looking forward to the imagery from Mars though, we promise to award huge bonus points for that.
