### ISSUE TITLE
API timeout - Unable to upload

### ISSUE THREAD

**Issue by james2432** [openstreetcam/openstreetview.org#154]
CameraHandlerService
1521243452155 V/CameraManagerOld: Releasing camera
1521243452155 D/CameraManagerOld: safeStopPreview
1521243452305 D/CameraManagerOld: safeStopPreview: kali destroyed texture
1521243452547 D/GoogleLocationManager: disconnect: disconnecting google api
1521243452552 D/EventBus: unregister: GoogleLocationManager
1521243473595 D/OsvRequestResponseListener: Volley error on request. Error: com.android.volley.TimeoutError
	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:168)
	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:133)

1521243473603 W/UploadManager: createSequence: ApiResponse{apiCode=-1, apiMessage='Unknown', httpCode=408, httpMessage='Timeout error'}
1521243473608 D/UploadManager: createSequence: creating sequence request
1521243473627 D/UploadManager: commitNextSequence: 1

**Comment by james2432** [comment]
seems to have come back oline finally

**Comment by alexandrui-telenav** [comment]
Hi James, checked the monitoring but couldn't find any downtime happening two days ago. 
You closed this issue two minutes after opening it, but did you experience that problem for a longer time before reporting?
Thanks!

**Comment by james2432** [comment]
yeah was trying to upload for an hour. Tried my wifi. Tried cell data. Nothing. Eventually it worked
