### ISSUE TITLE
missing 's'  on `/terms` page?

### ISSUE THREAD

**Issue by danbjoseph** [openstreetcam/openstreetview.org#159]
missing "s" in "use"
![screen shot 2018-04-30 at 2 18 45 pm](https://user-images.githubusercontent.com/4806884/39443070-697b504a-4c81-11e8-86cb-9267a447e4e4.png)

(same in current versions of both Chrome and Firefox)

**Comment by ciprianh-telenav** [comment]
Fixed, thank you, Dan!
