### ISSUE TITLE
Outdated map tiles in Ukraine

### ISSUE THREAD

**Issue by Andygol** [openstreetcam/openstreetview.org#16]
Decommunisation process is happening in Ukraine - a lot of place names have been changed. Your map still contains names that are no longer relevant. It would be good if the tiles will be re-generated to show the new names.

For example:
http://openstreetview.org/map/@48.46017328524599,34.955406188964844,11z
Dnipropetrovsk -> Dnipro (http://www.openstreetmap.org/relation/1017311)

Just look at the amount of changes in names
http://pavlo-dudka.github.io/osm-pg-tests/test.html?map?decommunization#zoom=14&lat=49.44552&lon=32.04432
<img width="920" alt="quality assurance osm ukraine 2016-07-27 15-36-06" src="https://cloud.githubusercontent.com/assets/369696/17175407/0db24d10-5410-11e6-9308-98452c95df94.png">

**Comment by james2432** [comment]
When I talked to Martin he said it's because of the tilemill that they are using the tiles are over 2 years old in some places, they are working on a solution

**Comment by martijnv-telenav** [comment]
Correct, we are figuring out a better way to serve more current tiles. Thanks for the detailed report @Andygol !

**Comment by rwelty1889** [comment]
this ticket is pretty old, and so are many map tiles still. any ETA for updates?

**Comment by mvexel** [comment]
Something is cooking. @alexandrui-telenav knows more details on ETA of fresher tiles. Sorry folks this has taken forever!

**Comment by alexandrui-telenav** [comment]
The web tiles have been updated with fresh (-er) maps, from April 2018. The team's plan is to keep them updated, I'm closing the ticket until proven otherwise.

**Comment by NathanBlais** [comment]
Tiles in have not been updated in over a year in my area for over a year, is this normal?
