### ISSUE TITLE
license and OSM compatibility

### ISSUE THREAD

**Issue by danbjoseph** [openstreetcam/openstreetview.org#160]
OSC imagery is Creative Commons Attribution-ShareAlike 4.0 International ([terms](http://openstreetcam.com/terms)) and
> OpenStreetCam is an application developed by Telenav that collects, stores and distributes georeferenced street view imagery with the purpose of helping the OpenStreetMap® (“OSM”) community improve the quality of the map data.  

but that license has “incompatible share-alike and attribution requirements” with OSM’s ODbL ([link](https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility))

Mapillary explicitly notes a license exception for derived data going into OSM. I don’t see something similar on the OSC site?

**Comment by james2432** [comment]
duplicate of https://github.com/openstreetcam/openstreetview.org/issues/6
so much for the search function

**Comment by danbjoseph** [comment]
thank you @james2432 
you're right the issue does already exist
and thank you for alerting me to the fact that it's also gone unaddressed for almost 2 years
you're a delight
i wish the best to any project you decide to be a part of
