### ISSUE TITLE
Manually tag signs?

### ISSUE THREAD

**Issue by mds08011** [openstreetcam/openstreetview.org#163]
Is it possible to manually "tag" signs that get missed by the automated detection?  The options/filters seem to indicate that it is, but I can't figure out how to do this.  

For example, I have a track of photos taken while pulling up to a stop sign.  The detection algorithm was able to identify the sign in most of the photos, but did miss the sign in a few of them. Can I manually "tag" this stop sign to improve detection?

**Comment by alexandrui-telenav** [comment]
It's possible to do that on beta.openstreetcam.org. We didn't make that very public as we're still thinking about some moderation steps in case of vandalism. Please play nice :)
