### ISSUE TITLE
Sign reviews need more options

### ISSUE THREAD

**Issue by ShadowFoxNixill** [openstreetcam/openstreetview.org#164]
Right now there are for each sign two options: "Correct" or "Incorrect". Having used the review feature for just five minutes (my first tag was "incorrect" on a bus stop sign that got mistaken for a "no u-turn" sign), I think there are two more options that need adding:

1. "Correct, but conditional" - For signs that have subtext, such as "4:00pm to 7:00pm" or "except buses". Allow entering of said subtext.
2. "Correct, but for a different road" - For signs that are correctly detected by OSC, but don't actually apply to the road from which the picture was taken, such as this one:
![image](https://user-images.githubusercontent.com/1627071/41386691-b81add5a-6f50-11e8-9361-3576e21e1621.png)

Also, "incorrect" signs should let you choose what the sign actually is.

**Comment by alexandrui-telenav** [comment]
Good points @ShadowFoxNixill. The purpose of the validation is to help improving the image recognition accuracy. To that end, both cases are 'correct' and should be marked as such, as the detected feature is indeed the one in the photo.

For the first case, we'll add at some point the conditional signs detections/tagging ( things like hours, buses, days of the week, etc ). They will be treated as different signs at detection time then logically merged with the main sign to get an accurate map feature.

The second example is similar, we're currently working on sign positioning ( where we compute the actual coordinate of the sign and snap to a road segment ). That will come with another validation layer to make sure they're positioned correctly, but for sign recognition both cases are correct.
Thanks for trying out the validation thing!
