### ISSUE TITLE
Map imagery out of date

### ISSUE THREAD

**Issue by omgitsgela** [openstreetcam/openstreetview.org#165]
The base map imagery is severely out of date, making my OSC tracks not follow the correct roadways. Can we get a map update, please?

**Comment by james2432** [comment]
duplicate of https://github.com/openstreetcam/openstreetview.org/issues/16

**Comment by mds08011** [comment]
Per the developer's response in #16:
>The web tiles have been updated with fresh (-er) maps, from April 2018. The team's plan is to keep them updated, I'm closing the ticket until proven otherwise.
