### ISSUE TITLE
Missing traces from last week

### ISSUE THREAD

**Issue by jremillard** [openstreetcam/openstreetview.org#166]
Hi,

Look at the map https://openstreetcam.org/map/@41.70600885920241,-70.08733391761781,16z

username jremillard

Azalea Drive was driven in the same trace as all of the side streets but isn't showing up on the map.

**Comment by mds08011** [comment]
It appears to be showing now (I am checking 11 days after your report):  https://openstreetcam.org/details/1258153/1534/track-info

Is this still an issue?

**Comment by jremillard** [comment]
It looks good now.
