### ISSUE TITLE
Photos stuck/No points

### ISSUE THREAD

**Issue by james2432** [openstreetcam/openstreetview.org#168]
http://openstreetcam.org/details/1276423/0/track-info

http://openstreetcam.org/details/1275961/0/track-info

http://openstreetcam.org/details/1275667/0/track-info

http://openstreetcam.org/details/1275659/0/track-info

all of them were uploaded through the latest android application and are done uploading

**Comment by alexandrui-telenav** [comment]
sorry @james2432 , fixed the problem, you have the points now.

**Comment by pkoby** [comment]
I didn't want to open a new ticket if possible, so hopefully this gets seen.

My latest uploads haven't gotten points either (http://openstreetcam.org/user/pkoby). This has been since Friday the 21st, but I only just noticed it.
