### ISSUE TITLE
ampersand in username

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [openstreetcam/openstreetview.org#172]
My username is &ergio, not ergio!

https://openstreetcam.org/user/ergio
https://www.openstreetmap.org/user/&ergio

**Comment by james2432** [comment]
ampersand is a url reserved character, name might need to be url encoded

**Comment by c-e-p-x-u-o** [comment]
But it works fine on osm.org

**Comment by alexandrui-telenav** [comment]
We do filter special characters in the URL. Other platforms besides OSM most likely filter those too.
The profile page displays the full username but the URL will not, sorry.
