### ISSUE TITLE
Rank on profile page does not correspond with rank in leaderboard

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/openstreetview.org#3]
My profile page says I am 23rd and the leaderboard says I'm 16th overall. Which is it?

<img width="566" alt="screenshot 2016-07-21 14 30 48" src="https://cloud.githubusercontent.com/assets/120452/17037778/bfda3716-4f4f-11e6-8040-e2e4f27ae899.png">

<img width="1198" alt="screenshot 2016-07-21 14 31 17" src="https://cloud.githubusercontent.com/assets/120452/17037790/d026530c-4f4f-11e6-8245-f1bea3ab4a17.png">

**Comment by james2432** [comment]
@martijnv-telenav this can be closed
