### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by mvexel** [openstreetcam/openstreetview.org#40]
the web site / API does not support https. It should.

**Comment by james2432** [comment]
Especially that you can get free ssl certs from letsencrypt

**Comment by rugk** [comment]
@openstreetview Any news?

**Comment by ToeBee** [comment]
I just had the same thought. HTTPS seems to now be available but it uses a self-signed certificate so browsers don't trust it.

**Comment by gappleto97** [comment]
Well, the website supports https now. The images are being loaded over http, though, so it's only a partial victory.
