### ISSUE TITLE
Can't view the images when click on the track

### ISSUE THREAD

**Issue by Xevib** [openstreetcam/openstreetview.org#48]
I can't view the images when click on the track.
This happens with the images of this zone http://openstreetview.org/map/@41.97747829378678,2.812703847885132,18z
I seen this error with Firefox and Chromium

**Comment by krl0z-cor3** [comment]
lo mismo sucede en esta zona 
http://openstreetview.org/map/@19.40526281579923,-99.16106879711151,18z 
pero no así en todo el trayecto, 
se necesita ir dando click a todo el trayecto para ver cual imagen se puede abrir, ya cuando se ven las imagenes puedes ver el trayecto completo.

**Comment by bogdans-telenav** [comment]
@Xevib Is this bug still reproducing for you?
