### ISSUE TITLE
Add search Bar

### ISSUE THREAD

**Issue by ghost** [openstreetcam/openstreetview.org#5]

**Comment by martijnv-telenav** [comment]
@ghost For geocoding? Like searching for cities etcetera?

**Comment by TheDutchMan13** [comment]
This my issue request. And yes.

**Comment by hamlet** [comment]
:+1: 

You have a few plugins to do just that with Leaflet:
http://leafletjs.com/plugins.html#geocoding

I've used the [Leaflet Control Geocoder](https://github.com/perliedman/leaflet-control-geocoder) with success.

It would be really useful to quickly get to your area of interest (not everyone map in california) ! :-)

**Comment by ToeBee** [comment]
Can this be closed? I see a geocoding search box on the website now.

**Comment by james2432** [comment]
@martijnv-telenav this can be closed.
