### ISSUE TITLE
Render bug with Uploaded Track preview images

### ISSUE THREAD

**Issue by minty** [openstreetcam/openstreetview.org#72]
Firefox 48.0.1 on MacOS 10.11.6

Depending on the width of the browser window, the preview images for each track disapear.

Three attached images - narrower (works), medium (missing preview thumbnails), larger (works).

<img width="1176" alt="screen shot 2016-08-30 at 10 41 43" src="https://cloud.githubusercontent.com/assets/89659/18086502/22e01408-6ea8-11e6-8008-1fbebd6bd25e.png">
<img width="1224" alt="screen shot 2016-08-30 at 10 41 51" src="https://cloud.githubusercontent.com/assets/89659/18086500/22dcbf4c-6ea8-11e6-8b0f-1dcab5f5c49c.png">
<img width="1387" alt="screen shot 2016-08-30 at 10 42 06" src="https://cloud.githubusercontent.com/assets/89659/18086501/22dd3468-6ea8-11e6-878a-960d3dab68f0.png">

and a small video (wrapped inside a zip file so GH will allow me to upload it) showing the problem.

[osv-render-thumbnails.zip](https://github.com/openstreetview/openstreetview.org/files/444720/osv-render-thumbnails.zip)

**Comment by minty** [comment]
ps. Same problem in Chrome 51.0.2704.103 (64-bit) on MacOS

**Comment by drkludge** [comment]
I noticed the problem yesterday.  I wasn't seeing images on Chrome and Firefox but they work properly on Android Chrome.  I increased the size of Chrome and Firefox because they were not full screen and the images appear.
