### ISSUE TITLE
Navigation in website displays random track sequences from around the world.

### ISSUE THREAD

**Issue by drkludge** [openstreetcam/openstreetview.org#76]
1.Go to an account.  I started at the leader board location. http://www.openstreetview.com/user/Dr%20Kludge
2.Select a track sequence. http://www.openstreetview.com/details/16255/0
3.Click on X.  I don't recall if I reviewed pictures in the sequence.

![image](https://cloud.githubusercontent.com/assets/1669057/18170179/33014ab2-7012-11e6-874f-b1e3f38bbae0.png)
4.I am correctly taken back to my account but the pictures are from Germany or other random parts of the world including my track sequences.

![image](https://cloud.githubusercontent.com/assets/1669057/18170227/6e69dbd2-7012-11e6-9cfe-92b2988102fc.png)

**Comment by alexandrui-telenav** [comment]
Thanks @drkludge, in some cases we reproduced this bug as well. I added it to the backlog to be fixed. I'll update the status once it's fixed.
