### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by martijnv-telenav** [openstreetcam/openstreetview.org#79]
Related to #54 -- can we re-introduce IP geolocation on load? And can we save the user's last visited location so they return there when they revisit the web site?

**Comment by trailblazr** [comment]
same here. it is totally annoying the map always starts in california. at least make the default zoom level show the whole world to allow picking you own location easily.

**Comment by scruss** [comment]
yes, we're not _all_ west coast techbros with self-driving te$$$las getting better routing to work off the free labour of other rubes

**Comment by moenk** [comment]
As there is an assigned issue from September still open - is this project still alive? 
If yes then there are modules to do this in leaflet quite simple: http://leafletjs.com/plugins.html#geolocation

**Comment by james2432** [comment]
Beta.openstreetcam.org atleast has a search bar
