### ISSUE TITLE
Some tracks in "Processing" state since very long time

### ISSUE THREAD

**Issue by Bch78** [openstreetcam/openstreetview.org#85]
Hi,
i have 3 tracks from my account in the "processing" state since a very long time (_more than one month for the oldest_):
- track  21383 in processing since 2016-09-12 (16:37)
- track  21385 in processing since 2016-09-12 (17:45)
- track  24165 in processing since 2016-10-03 (17:59)

Please advise: how is it possible to complete the processing ?

Thanks 

Best regards

**Comment by james2432** [comment]
Does it have the # of km or miles beside the listing or is it just [blank] km

**Comment by Bch78** [comment]
The 3 "processing" tracks have the same characteristics:
- a green badge with "PROCESSING" in the top of  the picture
- the #km is correctly displayed
- BUT this #kms (and the #images) have not been taken into account in the "Total KM" and "Total Images" assigned to my Profile

Below the screenshot of 2 of these 3 tracks.

![tracks](https://cloud.githubusercontent.com/assets/22785054/19307675/0e6ae1ba-907c-11e6-81a2-7ac0e0c8324d.png)

Regards

**Comment by james2432** [comment]
Then there is something definitly wrong in the back end. The reason I asked you about kms is because sometimes the "send Finish" doesnt get sent due to network timeout, but doesnt seem this is the case

**Comment by Bch78** [comment]
I have this other problem too:
- i have 10 tracks NOT TAKEN  into account in my profile
- and for these 10 tracks, the characteristics are the following
      =>  the #images is correct 
      =>  and the #KM is  blank
      => they do NOT have the green badge with "PROCESSING"

Exemples:
![tracks2](https://cloud.githubusercontent.com/assets/22785054/19308150/6a660a6a-907e-11e6-950e-5834f3fe1bb3.png)


How is it possible to correct these 2 problems ?
- the tracks with the PROCESSING state 
- the tracks with #KM left blank

**Comment by james2432** [comment]
The blank km are an easy fix, do you use the python scripts to upload?

**Comment by Bch78** [comment]
Yes i use the python scripts to upload
(but i have deleted the original tracks from my PC).

**Comment by james2432** [comment]
That doesn't matter:
1. Create an empty folder
2. Get the sequence id (I will use 9999 as an example)
3. Get the # of photos in that sequence and add 1 (I will use 777 as an example)
4. Create a text file in the empty folder called "count_file.txt" input the "777" on the first line and save
5. Create a text file in the empty folder called "sequence_file.txt" input the "9999" on the first line and save
6. Run the python script for that empty folder
7. It will send the "finished" command for that sequence and that sequence should start processing

**Comment by Bch78** [comment]
Ok, So i have created these two files (count_file.txt and sequence_file.txt) in a folder the i have run the script upload_photos_by_exif.py.

The error
   "Traceback (most recent call last):
       File "upload_photos_by_exif.py", line 455 in <module> main(sys.argv[1:])
       File "upload_photos_by_exif.py", line 438 in main
           if (index % 100 != 0) or index == 0:
      UnbounbLocalError: local variable 'index' referenced before assignment"
appears.

As i workaround, i have commented the lines 438 et 439 of the upload_photos_by_exif.py
   438:   #if (index % 100 != 0) or index == 0:
   439:   #      count_uploaded = thread(max_workers, ...)

After that, run again the script for the 10 tracks with the #KM blank:
==> Ok
==> the #KM is now completed with the correct value
==> the global counter "Total images", "Total tracks" and "Total KM" has also been 
       correctly upgraded.

Thanks a lot.

PS: 
So now i only have as problem the 3 tracks in the "PROCESSING" state.

**Comment by james2432** [comment]
that would be something telenav could help more with @martijnv-telenav

**Comment by moenk** [comment]
How long does an uploaded track need for processing anyway?

**Comment by james2432** [comment]
Right now they are about 5 days behind on processing tracks, there was a big backlog before(2 weeks or more) but they seemed to throw more servers at the problem.
